/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'admin-permissions-list': RouteRecordInfo<'admin-permissions-list', '/admin/permissions/list', Record<never, never>, Record<never, never>>,
    'admin-roles-list': RouteRecordInfo<'admin-roles-list', '/admin/roles/list', Record<never, never>, Record<never, never>>,
    'admin-users-list': RouteRecordInfo<'admin-users-list', '/admin/users/list', Record<never, never>, Record<never, never>>,
    'first-page': RouteRecordInfo<'first-page', '/first-page', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password-v1': RouteRecordInfo<'reset-password-v1', '/reset-password-v1', Record<never, never>, Record<never, never>>,
    'send-password-email': RouteRecordInfo<'send-password-email', '/send-password-email', Record<never, never>, Record<never, never>>,
    'verify-email': RouteRecordInfo<'verify-email', '/verify-email', Record<never, never>, Record<never, never>>,
  }
}
